import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import fonts from "@/assets/Font";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="appRoot" className={`${fonts.manrope.className} ${fonts.myGameGradual.variable}` }>{children}</body>
    </html>
  );
}
